package meshi.energy.ROT1solvation.parameters;

public interface WeightRepresentativePolars {
	final double[] weightRepresentativePolars = {
			0, //TRN 
			0, //TRC 
			0, //TRO 
			0, //AH  
			0, //AN  
			0, //ACA 
			0, //AC  
			0, //AO  
			0, //ACB 
			0, //CH  
			0, //CN  
			0, //CCA 
			0, //CC  
			0, //CO  
			0, //CCB 
			0, //CSG 
			0, //DH  
			0, //DN  
			0, //DCA 
			0, //DC  
			0, //DO  
			1.0, //DCB 
			0, //DCG 
			0.5, //DOD 
			0, //EH  
			0, //EN  
			0, //ECA 
			0, //EC  
			0, //EO  
			1.0, //ECB 
			0, //ECG 
			0, //ECD 
			0.5, //EOE 
			0, //FH  
			0, //FN  
			0, //FCA 
			0, //FC  
			0, //FO  
			0, //FCB 
			0, //FCG 
			0, //FCD 
			0, //FCE 
			0, //FCZ 
			0, //GH  
			0, //GN  
			0, //GCA 
			0, //GC  
			0, //GO  
			0, //HH  
			0, //HN  
			0, //HCA 
			0, //HC  
			0, //HO  
			1.0, //HCB    I changed this on 6/2/2009 for the pairwise potential
			0, //HCG 
			0, //HCD 
			0, //HND 
			0, //HHD 
			0, //HCE 
			0, //HNE 
			0, //HHE 
			0, //IH  
			0, //IN  
			0, //ICA 
			0, //IC  
			0, //IO  
			0, //ICB 
			0, //ICG1
			0, //ICG2
			0, //ICD 
			0, //KH  
			0, //KN  
			0, //KCA 
			0, //KC  
			0, //KO  
			1.0, //KCB 
			0, //KCG 
			0, //KCD 
			0, //KCE 
			1.0, //KNZ 
			0, //LH  
			0, //LN  
			0, //LCA 
			0, //LC  
			0, //LO  
			0, //LCB 
			0, //LCG 
			0, //LCD1
			0, //LCD2
			0, //MH  
			0, //MN  
			0, //MCA 
			0, //MC  
			0, //MO  
			0, //MCB 
			0, //MCG 
			0, //MSD 
			0, //MCE 
			0, //NH  
			0, //NN  
			0, //NCA 
			0, //NC  
			0, //NO  
			1.0, //NCB 
			0, //NCG 
			0.5, //NOD 
			0.5, //NND 
			0, //NHD1
			0, //NHD2
			0, //PN  
			0, //PCA 
			0, //PC  
			0, //PO  
			0, //PCB 
			0, //PCG 
			0, //PCD 
			0, //QH  
			0, //QN  
			0, //QCA 
			0, //QC  
			0, //QO  
			1.0, //QCB 
			0, //QCG 
			0, //QCD 
			0.5, //QOE 
			0.5, //QNE 
			0, //QHE1
			0, //QHE2
			0, //RH  
			0, //RN  
			0, //RCA 
			0, //RC  
			0, //RO  
			1.0, //RCB 
			0, //RCG 
			0, //RCD 
			0.33, //RNE 
			0, //RHE 
			0, //RCZ 
			0.33, //RNH 
			0, //SH  
			0, //SN  
			0, //SCA 
			0, //SC  
			0, //SO  
			1.0, //SCB 
			1.0, //SOG 
			0, //TH  
			0, //TN  
			0, //TCA 
			0, //TC  
			0, //TO  
			1.0, //TCB 
			0.5, //TCG 
			0.5, //TOG 
			0, //VH  
			0, //VN  
			0, //VCA 
			0, //VC  
			0, //VO  
			0, //VCB 
			0, //VCG1
			0, //VCG2
			0, //WH  
			0, //WN  
			0, //WCA 
			0, //WC  
			0, //WO  
			0, //WCB 
			0, //WCG 
			0, //WCD1
			0, //WCD2
			0, //WCE2
			0, //WCE3
			0, //WNE 
			0, //WHE 
			0, //WCZ2
			0, //WCZ3
			0, //WCH2
			0, //YH  
			0, //YN  
			0, //YCA 
			0, //YC  
			0, //YO  
			0, //YCB 
			0, //YCG 
			0, //YCD 
			0, //YCE 
			0, //YCZ 
			0  //YOH 
	};
}
